 AGENTS.md                                       |  13 [32m+[m
 docs/ENVIRONMENT_CHECK_02E.md                   |  93 [32m+++++++[m
 docs/HANDOFF.md                                 | 111 [32m++++++++[m
 docs/LOCAL_TEST_ACCEPTANCE.md                   |  62 [32m+++++[m
 docs/PROTOTYPE_02A.md                           |  72 [32m+++++[m
 docs/PROTOTYPE_02B.md                           |  67 [32m+++++[m
 docs/PROTOTYPE_02C.md                           | 126 [32m+++++++++[m
 docs/PROTOTYPE_02D.md                           |  85 [32m++++++[m
 docs/PROTOTYPE_02E.md                           |  89 [32m+++++++[m
 docs/PROTOTYPE_02F.md                           | 190 [32m+++++++++++++[m
 docs/PROTOTYPE_02G.md                           |  44 [32m+++[m
 docs/PROTOTYPE_02H.md                           |  47 [32m++++[m
 game/data/prototype_camera.tres                 |  14 [32m+[m
 game/data/prototype_combat.tres                 |  13 [32m+[m
 game/data/prototype_map.tres                    |   2 [32m+[m
 game/data/unit_mobile.tres                      |  13 [32m+[m
 game/data/unit_stationary.tres                  |   7 [32m+[m
 game/data/unit_unarmed.tres                     |   5 [32m+[m
 game/data/weapon_mobile.tres                    |   8 [32m+[m
 game/data/weapon_stationary.tres                |   8 [32m+[m
 game/scenes/maps/test_world.tscn                |   2 [32m+[m
 game/scripts/combat/combat_config.gd            |   8 [32m+[m
 game/scripts/combat/combat_config.gd.uid        |   1 [32m+[m
 game/scripts/combat/combat_simulation.gd        |  96 [32m+++++++[m
 game/scripts/combat/combat_simulation.gd.uid    |   1 [32m+[m
 game/scripts/combat/weapon_definition.gd        |   7 [32m+[m
 game/scripts/combat/weapon_definition.gd.uid    |   1 [32m+[m
 game/scripts/core/camera_config.gd              |  11 [32m+[m
 game/scripts/core/camera_config.gd.uid          |   1 [32m+[m
 game/scripts/core/game_world.gd                 | 340 [32m++++++++++++++++++++++[m[31m--[m
 game/scripts/core/local_camera.gd               | 178 [32m+++++++++++++[m
 game/scripts/core/local_camera.gd.uid           |   1 [32m+[m
 game/scripts/core/shot_visual.gd                |  18 [32m++[m
 game/scripts/core/shot_visual.gd.uid            |   1 [32m+[m
 game/scripts/maps/prototype_map_definition.gd   |   2 [32m+[m
 game/scripts/maps/test_map_geometry.gd          |  20 [32m++[m
 game/scripts/movement/movement_simulation.gd    | 198 [32m++++++++++++[m[31m--[m
 game/scripts/movement/route_cost_grid.gd        |  48 [32m++++[m
 game/scripts/movement/route_cost_grid.gd.uid    |   1 [32m+[m
 game/scripts/movement/static_navigation_grid.gd | 114 [32m++++++[m[31m--[m
 game/scripts/movement/terrain_surface.gd        |  64 [32m+++++[m
 game/scripts/movement/terrain_surface.gd.uid    |   1 [32m+[m
 game/scripts/networking/network_manager.gd      | 174 [32m++++++++++[m[31m--[m
 game/scripts/units/unit.gd                      |  77 [32m++++++[m
 game/scripts/units/unit_definition.gd           |  19 [32m++[m
 game/scripts/units/unit_definition.gd.uid       |   1 [32m+[m
 game/scripts/units/unit_state.gd                |  31 [32m+++[m
 game/tests/command_input_test.gd                |  82 [32m++++++[m
 game/tests/command_input_test.gd.uid            |   1 [32m+[m
 game/tests/prototype_01b_test.gd                |   2 [32m+[m
 game/tests/prototype_01c_test.gd                |  10 [32m+[m[31m-[m
 game/tests/prototype_01d_test.gd                |   8 [32m+[m[31m-[m
 game/tests/prototype_02a_test.gd                | 160 [32m+++++++++++[m
 game/tests/prototype_02a_test.gd.uid            |   1 [32m+[m
 game/tests/prototype_02b_test.gd                | 147 [32m++++++++++[m
 game/tests/prototype_02b_test.gd.uid            |   1 [32m+[m
 game/tests/prototype_02c_test.gd                | 239 [32m+++++++++++++++++[m
 game/tests/prototype_02c_test.gd.uid            |   1 [32m+[m
 game/tests/prototype_02d_test.gd                | 113 [32m++++++++[m
 game/tests/prototype_02d_test.gd.uid            |   1 [32m+[m
 game/tests/prototype_02e_test.gd                | 143 [32m++++++++++[m
 game/tests/prototype_02e_test.gd.uid            |   1 [32m+[m
 game/tests/prototype_02f_e2e.gd                 | 314 [32m++++++++++++++++++++++[m
 game/tests/prototype_02f_e2e.gd.uid             |   1 [32m+[m
 game/tests/prototype_02g_test.gd                |  89 [32m+++++++[m
 game/tests/prototype_02g_test.gd.uid            |   1 [32m+[m
 game/tests/prototype_02h_test.gd                | 186 [32m+++++++++++++[m
 game/tests/prototype_02h_test.gd.uid            |   1 [32m+[m
 scripts/start-local-test.ps1                    | 225 [32m++++++++[m[31m--------[m
 scripts/stop-local-test.ps1                     |  74 [32m++++[m[31m--[m
 70 files changed, 4052 insertions(+), 234 deletions(-)
