extends "res://tests/prototype_04c_test.gd"

func check(value: bool, label: String) -> void:
	checks += 1
	if value: print("PASS 0.4D: ",label)
	else:
		failures += 1
		push_error("FAIL 0.4D: " + label)

func _run() -> void:
	var economy := create()
	economy.register_player(1, 1, 0)
	economy.register_player(2, 1, 0)
	var settlements: Array[Dictionary] = []
	economy.event_emitted.connect(func(event: Dictionary):
		if event.kind == "settlement": settlements.append(event.duplicate(true)))
	for i: int in range(3):
		check(economy.register_live_unit(i+1,1,CONFIG.catalog[i].definition), "free test unit upkeep registration")
	var fee := 490.0 * 0.05 / 12.0
	check(is_equal_approx(economy.current_upkeep(1),fee), "body sortie cost, all live ground categories")
	check(not economy.register_live_unit(1,1,CONFIG.catalog[0].definition), "repeat registration cannot double charge")
	economy.advance_to_tick(299)
	check(economy.export_player(1).balance == 1000.0, "no premature debit")
	economy.advance_to_tick(300)
	check(is_equal_approx(economy.export_player(1).balance,1025-fee), "combined first settlement")
	check(economy.export_player(2).balance == 1025, "account isolation")
	economy.advance_to_tick(300)
	check(settlements.size()==2, "repeat tick cannot settle twice")
	economy.advance_to_tick(3600)
	check(is_equal_approx(economy.export_player(1).balance,1300-24.5), "fractional minute accumulation")
	check(economy.export_player(1).display_points == int(1300-24.5), "UI truncates, internal precision retained")
	economy.remove_live_unit(1)
	economy.remove_live_unit(1)
	check(economy.card_counts(1,"test.armored").present==0 and is_equal_approx(economy.current_upkeep(1),190*0.05/12), "death/legal removal releases slot and fee once")
	economy.begin_tick(3900)
	economy.register_live_unit(10,1,CONFIG.catalog[0].definition,3900)
	economy.advance_to_tick(3900)
	check(is_equal_approx(economy.export_player(1).last_settlement_upkeep,190*0.05/12), "boundary-tick birth billed next time")
	economy.advance_to_tick(4200)
	check(is_equal_approx(economy.export_player(1).last_settlement_upkeep,fee), "new unit billed next boundary")
	var order := economy.buy_order(2,"test.armored","ground.west")
	check(order.ok and economy.current_upkeep(2)==0, "held reservation no upkeep")
	economy.place_order(2,order.order_id,Vector3(-12,0,115))
	check(economy.current_upkeep(2)==0, "countdown no upkeep")
	economy.begin_tick(4380)
	var blocker := UnitState.new(99,0,Vector3(-12,0.5,112))
	blocker.configure(1,CONFIG.catalog[0].definition)
	blocker.position=Vector3(-12,0.5,112)
	var blocked: DeploymentConfig = CONFIG.duplicate(true)
	blocked.spawn_search_radius=0.1
	var waiting := create(blocked)
	waiting.register_player(1,1,0)
	var wait_order := waiting.buy_order(1,"test.armored","ground.west")
	waiting.place_order(1,wait_order.order_id,Vector3(-12,0,115))
	waiting.advance_to_tick(300)
	waiting.execute_deployments({99:blocker},func(_a,_b,_c,_d): return 100)
	check(waiting.export_player(1).orders[0].status=="waiting" and waiting.current_upkeep(1)==0, "blocked waiting charged no upkeep")
	waiting.cancel_order(1,wait_order.order_id)
	waiting.cancel_order(1,wait_order.order_id)
	check(waiting.export_player(1).balance==1025 and waiting.current_upkeep(1)==0, "cancel full refund once, no upkeep")
	var deploy := create()
	var deploy_id := order(deploy,"test.armored")
	advance(deploy,180)
	check(deploy.card_counts(1,"test.armored")=={"present":1,"pending":0} and is_equal_approx(deploy.current_upkeep(1),1.25), "generation converts reservation and registers upkeep")
	check(not deploy.cancel_order(1,deploy_id).ok, "generated order cannot refund")
	deploy.advance_to_tick(300)
	check(deploy.export_player(1).balance==723.75, "first generated-unit maintenance")
	deploy.remove_live_unit(deploy._orders[deploy_id].unit_id)
	check(deploy.buy_order(1,"test.armored","ground.west").ok, "death releases card for repurchase")
	var expensive: DeploymentConfig = CONFIG.duplicate(true)
	expensive.catalog[0].sortie_points=12000
	var poor := create(expensive)
	poor.register_player(1,1,0)
	for id: int in range(1,5): poor.register_live_unit(id,1,expensive.catalog[0].definition)
	poor.advance_to_tick(600)
	check(poor.export_player(1).balance==650, "multiple live units maintenance exceeds income")
	poor.advance_to_tick(1800)
	check(poor.export_player(1).balance==0 and not poor.buy_order(1,"test.unarmed","ground.west").ok, "zero floor and insufficient purchase")
	for id: int in range(1,5): poor.remove_live_unit(id)
	poor.advance_to_tick(2400)
	check(poor.export_player(1).balance==50 and poor.buy_order(1,"test.unarmed","ground.west").ok, "income recovers purchasing after removal")
	check(is_equal_approx(CONFIG.air_upkeep_fraction_per_minute,0.025), "air rate reserved only")
	print("0.4D checks=",checks," failures=",failures)
	quit(0 if failures==0 else 1)
